#!/bin/bash

export LISTEN_IP="0.0.0.0"
export SELF_IP=$(dig +short $(hostname))
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1}"
export DISABLE_MLOCK="${DISABLE_MLOCK:-false}"

render.py /etc/templates/vault.conf.j2 > /etc/vault/vaut.conf

echo "config:"
cat /etc/vault/vaut.conf | while read line; do echo -e "\t$line"; done
exec /usr/local/sbin/vault server -config /etc/vault/vaut.conf
