#!/bin/bash

export LISTEN_IP="0.0.0.0"
SELF_IP=$(dig +short $(hostname))
while [ "$SELF_IP" == "" ]; do
  sleep 1
  SELF_IP=$(dig +short $(hostname))
done
export SELF_IP
export CONSUL_ADDR="${CONSUL_ADDR:-127.0.0.1:8500}"
export DISABLE_MLOCK="${DISABLE_MLOCK:-false}"
export DISABLE_CONSUL_REGISTRATION="${DISABLE_CONSUL_REGISTRATION:-0}"

if [[ -n "${SERVICE_NAME}" ]]; then
  MIN_NODES_SIZE="${MIN_NODES_SIZE:-3}"
  echo "swarm mode enabled: peers are behind $(dig +short $SERVICE_NAME) ip"
  while [[ $number_of_nodes -lt ${MIN_NODES_SIZE} ]]; do
    sleep 1
    NODES=$(dig +short tasks.${SERVICE_NAME})
    number_of_nodes=$(( $(echo $NODES | grep -o '\s' | wc -l) + 1 )) >/dev/null
    echo "we found $number_of_nodes nodes"
  done
fi

render.py /etc/templates/vault.conf.j2 > /etc/vault/vaut.conf

echo "config:"
cat /etc/vault/vaut.conf | while read line; do echo -e "\t$line"; done
exec /usr/local/sbin/vault server -config /etc/vault/vaut.conf
